language: ruby
rvm:
  - 2.0
  - 2.5
  
services:
  - docker
  
stage: test

script:
  - cd docker && ./run_tests.sh

jobs:
  include:
    - stage: gem release
      rvm: 2.0
      script: echo "Deploying to rubygems.org ..."
      deploy:
        provider: rubygems
        api_key: $RUBYGEMS_KEY
        gemspec: docker_toolkit.gemspec


