
language: ruby
rvm:
  - 2.0
  - 2.5
  
services:
  - docker
  
stage: test

before_install:
  - sudo apt-get install -y libxml2-dev unzip curl
  
script:
  - gem build `ls | grep gemspec`
  - gem install `ls | grep -e '.gem$'`
  - curl -sSLo /tmp/consul.zip https://releases.hashicorp.com/consul/1.2.1/consul_1.2.1_linux_amd64.zip 
  - sudo unzip -d /bin /tmp/consul.zip 
  - bundle exec rspec


jobs:
  include:
    - stage: gem release
      rvm: 2.0
      script: echo "Deploying to rubygems.org ..."
      deploy:
        provider: rubygems
        api_key: $RUBYGEMS_KEY
        gemspec: docker_toolkit.gemspec


